services:

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:  
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
       - pgadmin:/var/lib/pgadmin
       
volumes:
    postgresql_data:
    pgadmin: